### ISSUE TITLE
Include information on which feature line failed in failure message

### ISSUE THREAD

**Issue by tommilligan** [bencompton/jest-cucumber#116]
I'm using the `autoBindSteps` features of the library, to write tests directly in `*.feature` files.

When a step fails, a failure message is generated such as:
```log
  ● Feature name > Scenario name

    expect(received).toBeTruthy()

    Received: false

      88 |     /^I should expect '(.*)' to equal '(.*)'$/,
      89 |     async (left: string, right: string) => {
    > 90 |       expect(left).toEqual(right);
         |                     ^
      91 |     },
      92 |   );

      at Object.stepFunction (src/step-definitions/demo.ts:90:21)
      at node_modules/jest-cucumber/src/feature-definition-creation.ts:134:65
          at runMicrotasks (<anonymous>)
```

This allows me to find the underlying step definition that failed, but not the source line in the feature file. Ideally, I would see:

```log
  ● Feature name > Scenario name

    jest-cucumber: Then I should expect 'foo' to equal 'bar' (src/features/demo.feature:15:4)

    expect(received).toBeTruthy()

    Received: false

      88 |     /^I should expect '(.*)' to equal '(.*)'$/,
      89 |     async (left: string, right: string) => {
    > 90 |       expect(left).toEqual(right);
         |                     ^
      91 |     },
      92 |   );

      at Object.stepFunction (src/step-definitions/demo.ts:90:21)
      at node_modules/jest-cucumber/src/feature-definition-creation.ts:134:65
          at runMicrotasks (<anonymous>)
```

This would allow me to point to the source line in the feature definition where the error occurred, especially when steps are reused many times:

```cucumber
    ...
    Then I should expect '1' to equal '1'
    Then I should expect 'foo' to equal 'bar'
    Then I should expect '1' to equal '1'
```

I'm happy to have a go at implementing this if the rough design looks acceptable?

**Comment by bencompton** [comment]
PR merged, so closing.
