### ISSUE TITLE
Scenarios fail with what appears to be Babel issue

### ISSUE THREAD

**Issue by InfoSec812** [bencompton/jest-cucumber#28]
My example project is https://github.com/InfoSec812/vuejs-bdd-primer

I'm trying to use jest-cucumber with VueJS 3.x and Quasar framework. 

When I go to run my tests `npm test` I get the following error which appears to be an issue with Babel, but I do not get similar errors when I run standard Jest unit tests.

```
$ npm run test:unit

> my-new-application@0.1.0 test:unit /home/dphillips/Documents/RedHat/Workspace/my-new-application
> vue-cli-service test:unit

 FAIL  tests/unit/steps/Home.steps.js
  ● Test suite failed to run

    TypeError: (0 , _typeof4.default) is not a function

      at _typeof2 (node_modules/@babel/runtime/helpers/builtin/typeof.js:12:60)
      at _typeof (node_modules/@babel/runtime/helpers/builtin/typeof.js:26:39)
      at node_modules/regenerator-runtime/runtime.js:36:86
      at Object.<anonymous> (node_modules/regenerator-runtime/runtime.js:724:2)

 FAIL  tests/unit/steps/Debugging.steps.js
  ● Test suite failed to run

    TypeError: (0 , _typeof4.default) is not a function

      at _typeof2 (node_modules/@babel/runtime/helpers/builtin/typeof.js:12:60)
      at _typeof (node_modules/@babel/runtime/helpers/builtin/typeof.js:26:39)
      at node_modules/regenerator-runtime/runtime.js:36:86
      at Object.<anonymous> (node_modules/regenerator-runtime/runtime.js:724:2)
```

Any assistance would be GREATLY appreciated!

**Comment by InfoSec812** [comment]
I made quite a bit more progress this evening and got past the Babel issues. I will be writing up a Primer on my blog when I have the whole example working. Anyone looking for a solution should go to: https://blog.zanclus.com/ and watch for that post.
