### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by kirilldev** [bencompton/jest-cucumber#73]
I am using jest-cucumber with an angular 6 project. There is a problem that if an error appears on template side angular generates an error object with a circular structure. 

Later when ScenarioResultFileOperations.saveScenarioResult is called I am getting an error.

  ```
TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)

      at node_modules/jest-cucumber/src/reporting/scenario-result-tracking/ScenarioResultFileOperations.ts:23:30
      at new ZoneAwarePromise (node_modules/zone.js/dist/zone.js:910:29)
      at Object.<anonymous>.exports.saveScenarioResult (node_modules/jest-cucumber/src/reporting/scenario-result-tracking/ScenarioResultFileOperations.ts:22:10)
      at ScenarioResultTracker.Object.<anonymous>.ScenarioResultTracker.endScenario (node_modules/jest-cucumber/src/reporting/scenario-result-tracking/ScenarioResultTracker.ts:36:4)
      at node_modules/jest-cucumber/src/feature-definition-creation.ts:161:22
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:131:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at node_modules/zone.js/dist/zone.js:889:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:423:31)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:162:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:422:60)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:195:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:601:35)
      at Object.<anonymous>.ZoneTask.invokeTask (node_modules/zone.js/dist/zone.js:502:21)
      at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:487:48)
      at timer (node_modules/zone.js/dist/zone.js:2281:29)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)

```

To fix the problem, instead of JSON.stringify we need to use something that can handle circular dependencies.

**Comment by bencompton** [comment]
That's an issue in the 2.0.12 reporting module, which needs to be re-worked so it doesn't use JSON serialization in the first place. 2.0.12 isn't under the latest tag and should be considered beta quality, so you might consider using 2.0.11 instead.

**Comment by bencompton** [comment]
This duplicates #27, so closing.
